on:
  pull_request:

jobs:
  job_1:
    runs-on: ubuntu-latest  
    steps:
      - name: cp ls
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.1/LLVM-19.1.1-Linux-X64.tar.xz
          cp LLVM-19.1.1-Linux-X64.tar.xz foo.tar.xz
          cp LLVM-19.1.1-Linux-X64.tar.xz foo2.tar.xz
          cp LLVM-19.1.1-Linux-X64.tar.xz foo3.tar.xz
          cp LLVM-19.1.1-Linux-X64.tar.xz foo4.tar.xz
          ls -l foo*
    
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ock
          path: foo.tar.xz
          retention-days: 5

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ock2
          path: foo2.tar.xz
          retention-days: 5

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ock3
          path: foo3.tar.xz
          retention-days: 5
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ock4
          path: foo4.tar.xz
          retention-days: 5

  job_2:
    name: do ls
    needs: job_1
    runs-on: ubuntu-latest  
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: ock
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: ock2
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: ock3
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: ock4
      - shell: bash
        run: |
          ls -l foo*

