on:
  pull_request:

jobs:
  job_1:
    runs-on: ubuntu-latest  
    steps:
      - name: cp ls
        run: |
          cp `which ls` myls
    
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ock
          path: myls
          retention-days: 5

  job_2:
    name: do ls
    needs: job_1
    runs-on: ubuntu-latest  
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: ock
      - shell: bash
        run: |
          chmod +x myls
          ./myls

