on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'Log level'
        default: 18
        type: choice
        options:
          - 17
          - 18
          - 19
      update_cache:
        description: 'update_cache'
        default: false
        type: boolean
  pull_request:

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Print the input tag to STDOUT
        run: |
         echo  The llvm_version are ${{ inputs.llvm_version }}, benchmark_testing is ${{ inputs.update_cache }}
         cat "$GITHUB_ENV"
         echo ${{ github.event }}
         echo "LLVM_VERSION=${{ inputs.llvm_version }}" >> $GITHUB_ENV"
         echo "UPDATE_CACHE=${{ inputs.update_cache }}" >> $GITHUB_ENV"

  # run-on-pull:
  #   if: ${{ github.event_name == 'pull_request' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print the input tag to STDOUT
  #       run: |
  #         echo  The llvm_version are ${{ inputs.llvm_version }}, update_cache is ${{ inputs.update_cache }}
  #         cat "$GITHUB_ENV"
  #         echo ${{ github.event }}
  #         echo "LLVM_VERSION=18" >> $env:GITHUB_ENV"
  #         echo "UPDATE_CACHE=false" >> $env:GITHUB_ENV"

  run-on-pull_2:
    name: Call other workflow
    if: ${{ github.event_name == 'pull_request' }}    
    # needs: run-on-pull
    uses: ./.github/workflows/workflow_callee.yml
    with:
      llvm_version: 18
      update_cache: true

