on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'Log level'
        default: 18
        type: choice
        options:
          - 17
          - 18
          - 19
      benchmark_testing:
        description: 'benchit'
        default: false
        type: boolean
  pull_request:

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.llvm_version }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The llvm_version are ${{ inputs.llvm_version }}, benchmark_testing is ${{ inputs.benchmark_testing }}

  run-on-pull:
    if:  ${{ inputs.llvm_version }} != ""   
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The llvm_version are ${{ inputs.llvm_version }}, benchmark_testing is ${{ inputs.benchmark_testing }}